name: ShoppingCart CI

on: [push]
  

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dotnet: ['3.1.x']
    name: Dotnet ${{matrix.dotnet}} build
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - run: dotnet build ShoppingCart
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
    - run: |
          docker build -t cart ShoppingCart
          docker tag cart 2526m/userapirepo
          docker push ${{ secrets.DOCKER_HUB_REPOSITORY }}
    - name: Create SSH key
      run: |
          mkdir -p ~/.ssh/
          echo "$RSA_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$KNOWN_HOST" > ~/.ssh/known_hosts
      shell: bash
      env:
        SSH_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}
        SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOST}}
        SSH_KEY_PATH: ${{ github.workspace }}/../private.key
    - name: Shell into Server 
      run: |
          pwd
          ls -la
          ssh -i ${{ github.workspace }}/../private.key ec2-user@52.14.87.147
          sudo docker images
          exit
